// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using assignment2.Models;

#nullable disable

namespace assignment2.Migrations
{
    [DbContext(typeof(Traineedb16Context))]
    partial class Traineedb16ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("assignment2.Models.Employeee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"), 1L, 1);

                    b.Property<int?>("ContactNo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HomeAddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("('true')");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("WorkLocation")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmpId")
                        .HasName("PK__Employee__AF2DBB9959CDF39F");

                    b.ToTable("Employeee", (string)null);
                });

            modelBuilder.Entity("assignment2.Models.Hr", b =>
                {
                    b.Property<int>("HrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HrId"), 1L, 1);

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<string>("EmpPayrollInfo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Salary")
                        .HasColumnType("int");

                    b.Property<int?>("SocialSecurityNo")
                        .HasColumnType("int");

                    b.HasKey("HrId");

                    b.HasIndex("EmpId");

                    b.ToTable("Hr", (string)null);
                });

            modelBuilder.Entity("assignment2.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("locationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int")
                        .HasColumnName("buildingId");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("managerName");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int")
                        .HasColumnName("zipCode");

                    b.HasKey("LocationId");

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("assignment2.Models.Hr", b =>
                {
                    b.HasOne("assignment2.Models.Employeee", "Emp")
                        .WithMany("Hrs")
                        .HasForeignKey("EmpId")
                        .HasConstraintName("FK__Hr__EmpId__681373AD");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("assignment2.Models.Employeee", b =>
                {
                    b.Navigation("Hrs");
                });
#pragma warning restore 612, 618
        }
    }
}
